version: '3'
services:
  db:
    image: postgres:9.5-alpine
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/myapp:rw
      - data-tmp:/myapp/tmp
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    dns:
      - 8.8.8.8
volumes:
  data-tmp:
    driver: local
  data-postgres:
    driver: local
  bundle:
    driver: local
