version: '3'
services:
  db:
    image: postgres:9.5-alpine
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/myapp:rw
      - data-tmp:/myapp/tmp
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    dns:
      - 8.8.8.8
  #elasticsearch:
   # image: elasticsearch:5.6.9-alpine
    #env_file: .env
    #container_name: elasticsearch
    #command: [elasticsearch, -E, network.host=0.0.0.0]
    #ulimits:
#      nproc: 4096
    #  memlock:
    #    soft: -1
    #    hard: -1
    #  nofile:
    #    soft: 65536
    #    hard: 65536
    #volumes:
    #  - esdata:/usr/share/elasticsearch/data:rw
    #ports:
    #  - 9200:9200
    #  - 9300:9300

volumes:
  data-tmp:
    driver: local
  data-postgres:
    driver: local
  bundle:
    driver: local
  #esdata:
    #driver: local
