source 'https://rubygems.org'

gem 'bcrypt', require: 'bcrypt'
gem 'best_in_place'
gem 'bootstrap-sass', '3.1.1.0'
gem 'carrierwave', '~> 0.11.0'
gem 'carrierwave-dropbox', git: 'git@github.com:mful/carrierwave-dropbox.git'
gem 'ckeditor', '4.1.3'
gem 'coffee-rails', '~> 4.2'
gem 'dotenv-rails'
gem 'font-awesome-rails'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'pg'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.2'
gem 'remotipart', '~> 1.3', '>= 1.3.1'
gem 'sass-rails', '~> 5.0'
gem 'slim-rails', '~> 3.1', '>= 3.1.2'
gem 'social-share-button'
gem 'turbolinks', '~> 5'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate', '~> 3.1', '>= 3.1.5'

group :development, :test do
  gem 'annotate', '~> 2.4.1.beta1'
  gem 'awesome_print', '~> 1.7'
  gem 'better_errors', '~> 2.1', '>= 2.1.1'
  gem 'bootstrap-generators', '~> 3.3.4'
  gem 'bootstrap-will_paginate', '~> 1.0'
  gem 'bullet'
  gem 'byebug', platform: :mri
  gem 'factory_girl_rails'
  gem 'faker', '~> 1.7', '>= 1.7.3'
  gem 'listen', '~> 3.0.5'
  gem 'pry'
  gem 'rspec-rails', '~> 3.5'
  gem 'rubocop', '~> 0.48.1'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'test-unit', '~> 3.2', '>= 3.2.3'
  gem 'web-console', '>= 3.3.0'
end
